# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts 'clearing database..'
Video.destroy_all
Ski.destroy_all
Article.destroy_all
Resort.destroy_all
puts 'creating videos..'

# always in title puts long titles

Video.create!(title: "GoPro Snow: Jesper Tjäder's Forest", url: "cXYep0_5qOY", region: "Austria", rating: 6)
Video.create!(title: "POV Series #1 | The Faction Collective", url: "-4tsX20dPX0", region: "France", rating: 8)
Video.create!(title: "GoPro: Chasing Adventure - Crhis Bentchelter", url: "PNs68O5JSKg", region: "Usa", rating: 10)
Video.create!(title: "GoPro Ski: Chasing El Niño - ep:2", url: "lZE66YL0V8I", region: "Usa", rating: 9)
Video.create!(title: "GoPro Ski: Chasing El Niño - ep:3", url: "N5XIWU017kU", region: "Usa", rating: 9)
Video.create!(title: "GoPro Ski: Chasing El Niño - ep:4", url: "Z1OQbLqtVLE", region: "Usa", rating: 9)
Video.create!(title: "The Faction Collective Presents: La Grave", url: "QkinG08IoKk", region: "France", rating: 8)
Video.create!(title: "The Faction Collective Presents: British Columbia", url: "k0xxtEqeBog", region: "Canada", rating: 8)
Video.create!(title: "THIS IS HOME - Duncan Adams: Athlete Edit", url: "MUw2_EbqOgU", region: "Europe", rating: 5)
Video.create!(title: "THIS IS HOME - Antti Ollila: Athlete Edit", url: "9Tv99c2tTMw", region: "Austria", rating: 5)
Video.create!(title: "We Are The Faction Collective: Ep02", url: "rGsNEAx7U1I", region: "Usa", rating: 7)
Video.create!(title: "THIS IS HOME - Utah Segment-Faction skis", url: "q3glYu4IyZI", region: "Usa", rating: 8)
Video.create!(title: "THIS IS HOME - Extended Cut: Zermatt", url: "u_GnIMxHY7M", region: "Suiza", rating: 8)
Video.create!(title: "We Are The Faction Collective:Ep01", url: "qp6NV33XAc8", region: "Argentina", rating: 7)
Video.create!(title: "We Are The Faction Collective:Ep03", url: "MPKdL_E-z7s", region: "Suiza", rating: 7)
Video.create!(title: "Armada Presents SNOWCIETIES Chamonix", url: "goD_ewMlSj8", region: "France", rating: 8)
Video.create!(title: "THIS IS HOME - Rough Cut: Finland", url: "Wfwm2P1stK8", region: "Finland", rating: 6)
Video.create!(title: "Armada Family Profile: Torin Yater-Wallace", url: "vkkiDOSYvRk", region: "Usa", rating: 6)
Video.create!(title: "GoPro: Tanner Hall Ski Diaries Ep:2", url: "g0FMrjsYAzc", region: "Usa", rating: 8)
Video.create!(title: "GoPro: Tanner Hall Ski Diaries Ep:1", url: "N2CWCJJilfk", region: "Usa", rating: 7)
Video.create!(title: "GoPro Line of the Winter: Léo Taillefer", url: "UYmcm5bKvxk", region: "France", rating: 7)
Video.create!(title: "GoPro Line of the Winter: Nicolas Falquet", url: "EMVPpPE_Bx4", region: "Suiza", rating: 8)
Video.create!(title: "Eric Pollard & Line Skis Shred Mt Hood", url: "ivG4ZHt5e4c", region: "Usa", rating: 7)
Video.create!(title: "Introducing the LINE Sakana by Eric Pollard", url: "wBpbZ1aeWtQ", region: "Usa", rating: 5)
Video.create!(title: "REJOICE: SAMMY CARLSON - Quicksilver trailer", url: "lqdJarUoXow", region: "Usa", rating: 6)
Video.create!(title: "Few Words Trailer - The Candide Thovex movie", url: "eL2sCAvM29A", region: "France", rating: 8)
Video.create!(title: "Candide Kamera Episode 2 - Quicksilver", url: "BuL7SSP_dH0", region: "France", rating: 7)
Video.create!(title: "One of those days - Candide Thovex", url: "ygxufRprWpY", region: "France", rating: 10)
Video.create!(title: "One of those days 2 - Candide Thovex", url: "yKP7jQknGjs", region: "France", rating: 10)
Video.create!(title: "One of those days 3 - Candide Thovex", url: "R1NagZN2kjY", region: "France", rating: 9)
Video.create!(title: "Candide Thovex - quattro 2 - Audi", url: "NHrwcQQ38bA", region: "France", rating: 9)
Video.create!(title: "Random Shots - Candide Thovex", url: "2aXFPZjCsok", region: "France", rating: 9)
Video.create!(title: "Few Words - A Candide Thovex Film", url: "cpi2fc5vfNs", region: "France", rating: 9)
Video.create!(title: "GoPro Ski: Chasing El Niño – Ep. 1 ", url: "hqtDehAtAN8", region: "Usa", rating: 8)
Video.create!(title: "GoPro: New Zealand Adventure - Chris Bentchelter", url: "aRm-JTO70F0", region: "New_Zeland", rating: 9)
Video.create!(title: "GoPro: Japan - The Search for Perfection in 4K", url: "tXpXHoDKL64", region: "Japan", rating: 9)
# Video.create!(title: "", url: "", region: "", rating: )


puts 'creating skis..'
 Ski.create!(name: "Head Kore", description: "HEAD’s award-winning KORE series was met with rabid enthusiasm when it debuted last winter, so it makes perfect sense that the brand has added a versatile 99-mm waist width to the family for 2018-19.
  “This ski has no compromises,” commented Adrian Bouthot. “It has a super fun waist width and would be an ideal one ski quiver that excels in a lot of areas.” The Head Kore 99 utilizes the same construction found in the rest of
  the family—lightweight karuba wood, incredibly strong yet thin Graphene, rockered tips and tails with camber underfoot—but in a waist width that’s dreamy in a few inches of fresh or the chopped up crud from last week’s storm", brand: "Head", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Kore105.png", category: "All-mountain",
  price: "699", url: "head-kore-99#image=138622/574864/head-kore-99-skis-2019-162.jpg")
Ski.create!(name: "Blizzard Rustler 11", description: "Adrian Bouthot described the Blizzard Rustler 11 pretty perfectly, stating, “Checks all the boxes for a skier that likes to push the speed barrier everywhere.”
 Blizzard threw a whole lot into the mixing pot to create this high-performance rig.
 A combination of balsa, paulownia, poplar and beech woods in the core cover the bases of dampening, spring, weight savings and rigidity.
  Titanal underfoot with a full sandwich construction ensure power transmission, while two full-length layers of carbon and fiberglass provide even more lightweight strengthening.
   “Knives on both the groomers and in the pow,” said Sarina Scott. “A super stable ski with the ability to handle the highest speeds.”", brand: "Blizzard", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Rustler11.png", category: "All-mountain",
  price: "840", url: "blizzard-rustler-11#image=122272/511292/blizzard-rustler-11-skis-2018-164.jpg")
Ski.create!(name: "Line Sakana", description: "Spawned from the same DNA as the powder proven Pescado, the all-new Line Skis Sakana Skis bring the same directional, swallowtail creativity to a much more versatile 105mm waist width. Designed by the creative mind of Eric Pollard, the Sakana's wide forebody, directional flex and knocked out tail combine to create a ski that encourages a wide variety of turn shapes.
 Rediscover the euphoria of laying into carves—both on-and-off piste—with the playful, pioneering Line Sakana Skis. The revolution is here, don't get left behind.", brand: "Line", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Sakana.png", category: "All-Mountain",
  price: "800", url: "line-sakana#image=138259/567842/line-skis-sakana-skis-2019-174.jpg")
Ski.create!(name: "Armada Tracer 108", description: "The Tracer 108 puts equal focus on uphill efficiency and freeride performance. In fact, Armada calls it the love child of the featherweight Kufo 108 and hard-charging Norwalk. The ski weighs a manageable 1,885 grams per ski, but a stiff character—owed to camber underfoot and a stiff composite insert—ensures it
  can rip any backcountry zone to shreds. “These skis were incredible on the uphill,” explained Jacob Dalbey. “Even though they were super light on the up, they charged like a ’76 Corvette on the descent.”
  Those who consistently seek soft snow conditions in the backcountry and prefer a slightly wider waist width will find the Tracer 108 a trustworthy companion.", brand: "Armada", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Tracer108.png", category: "All-Mountain",
  price: "825", url: "armada-tracer-108#image=140313/580382/armada-tracer-108-skis-2019-164.jpg")
Ski.create!(name: "Armada ARV 96", description: "The Armada ARV 96 keeps you G’d up from the feet up just like that dachshund on its topsheet.
 A combination of springy poplar and stable ash wood in the core ensures this baby is playful, strong and responsive, all at once.
 A rockered tip and tail boost the ARV 96’s maneuverability, ideal for the skier that enjoys playing in the trees or floating through a couple inches of fresh.
 “Playful like the puppy that graces its topsheet,” surmised Tae Westcott, while Scott Kramer praised its hardpack capabilities, “Great ski for anybody. You can hit laps in the park and go rip some corduroy with absolute confidence.”", brand: "Armada", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/ARV96.png", category: "All-Mountain", price: "600", url: "armada-arv-96#image=140327/580365/armada-arv-96-skis-2019-163.jpg")
Ski.create!(name: "Faction CT 5.0", description: "The brainchild ski series of Candide Thovex (who many consider the G.O.A.T) takes the next step in its evolution with the Faction CT 5.0,
  meant to shine on the deepest of powder days as evidenced by its 122-mm waist width.
  “Super fun, quick-turning ski. Awesome for poppin’ off catwalks into the pow,” said Alex Golden.
  “Super stable, yet could still turn easily for such a fat ski,” added Bridget Boyle. Faction achieves this balance by combining a balsa, flax and poplar wood core for a lightweight yet responsive and stable ride.
  The CT 5.0 also uses what the brand calls a directional twin tip shape—camber underfoot and rocker in the tip and tail with a little less pronouncement in the tail to increase dependability at high speed on variable snow.
  It’s a hard charger that loves to play.", brand: "Faction", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/CT5.png", category: "Powder", price: "1059", url: "faction-candide-50#image=139337/589350/faction-candide-5-0-skis-2019-183.jpg")
Ski.create!(name: "K2 Marksman", description: "The K2 Marksman hits the bull’s eye of what an all-mountain freestyle ski should be.
  The ski was conceived by Pep Fujas and features an elongated taper on the outside edge, allowing for incredible quick-turn ability.
  Meanwhile the inner edge is longer for better edgehold and stability.
  The pairing of rigid ash wood along the edges and a lively aspen wood and carbon stringer duo down the gut boosts that versatility sought after by Pep and the gang at K2.
  “This is my favorite ski thus far,” said Thomas Lampert. “It did everything I wanted and responded, carved well, was super stable and oh-so-playful.”", brand: "K2", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Marksman.png", category: "All-Mountain", price: "750", url: "skis/k2-marksman#image=138346/570623/clone.jpg")
Ski.create!(name: "Line Sick Day 104", description: "“I am down with the sickness,” said FREESKIER editor Donny O’Neill in regard to the Line Sick Day 104.
  “These babies are just plain fun. They excel in all terrain—bumps, trees, airs, groomers.” Adrian Bouthot described them as “a great everyday ski for western skiers.”
  Line complements the Sick Day’s aspen wood core with carbon fiber laid from tip to tail to create a ski that’s lightweight, nimble and stable at the same time.
  Those ingredients paired with the ski’s rocker-camber-rocker profile make it a jackrabbit that wants to dart all over the mountain, all sick day long.
   And with that sexy retro topsheet, these planks won’t stay on the shelves for very long this fall.", brand: "Line", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/SickDay104.png", category: "All-Mountain", price: "750", url: "line-sick-day-104#image=138271/567874/line-skis-sick-day-104-skis-2019-172.jpg")
Ski.create!(name: "Atomic Bent Chetler 120", description: "The 2018-19 season marks the tenth anniversary of the very first Bent Chetler, and the powder planks have only gotten better with age—an attribute shared by its creator, Chris Benchetler.
 The Bent Chetler is a damn dream for surfing deep snow conditions, thanks to an ultra-light karuba wood core and HRZN Tech—horizontal rocker and lateral ABS sidewalls—in the tip and tails that transforms these babies into speed boats for the snow.
  Add in a carbon backbone and camber underfoot for stability, and you’ve got the whole package.
  “The poppiest pow ski ever,” described Adrian Bouthot. “Hops around like a butterfly but can put the landing gear down like a beast.”", brand: "Atomic", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Bentchetler120.png", category: "Powder", price: "900", url: "atomic-bent-chetler-120#image=138027/570120/atomic-bent-chetler-120-skis-2019-176.jpg")
Ski.create!(name: "Atomic Bent Chetler 100", description: "The Mini Me to the classic Bent Chetler fatty ski, its 100-mm waisted clone was a shagadelic hit among our testers.
 “The Bent Chetler series is always on point,” said Scott Kramer.
  “It’s about time they created a skinnier version ’cause this baby was a blast!” Thomas Lampert added, “I would pay retail for these bad boys.
   They cut trenches, are super playful—just good, clean fun.” As expected, the Atomic Bent Chetler 100 employs Atomic’s HRZN Tech, horizontally rockered ABS in the tip and tail, for an increase in surface area and buttery good times.
    It also boasts a slightly more directional shape than its father, allowing it to truly excel across the entire mountain. ", brand: "Atomic", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Bentchetler100.png", category: "All-Mountain", price: "600", url: "atomic-bent-chetler-100")
Ski.create!(name: "Blizzard Rustler 9", description: "Tester Adrian Bouthot called this ski, “the most accessible Rustler of them all.
  Anyone could get on this ski and have a blast. It’s stable enough for railing turns but also has some forgiveness for when you want to dial it back.”
  The Blizzard Rustler 9 is geared, in general, to those who spend the majority of their time ripping the frontside. The ski features a full camber construction and full-length sidewalls, giving it tremendous power.
   Blizzard implements specially shaped Titanal underfoot and unidirectionally-shaped carbon fiber in the tip and tail. This ensures torsional rigidity through the gut of the ski but a decrease in stiffness in the tip and tail for incredible maneuverability.", brand: "Blizzard", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Rustler9.png", category: "All-Mountain", price: "720", url: "blizzard-rustler-9#image=137870/581255/blizzard-rustler-9-skis-2019-164.jpg")
Ski.create!(name: "Black Crows Atris", description: "A repeat Editors’ Pick, the Black Crows Atris is the flagship model of Black Crows’ big-mountain line.
   “Another great ski from Black Crows,” commented Mikey Wechsler. “It’s a stable carver yet playful as hell off the groomed stuff.”
    Black Crows achieves this versatility via an energetic poplar wood core, as well as tip and tail rocker with a more radical rise in the tip for easy turning and planing through deep snow.
     Medium camber underfoot and an extended sidecut (over the previous model) allow it to perform like a sports car on groomers and hardpack. Drew Ingardia called it “one for the books.
      It maintains stability through crud, groomers and likes to spend time in the air!”", brand: "Black Crows", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Atris.png", category: "Powder", price: "800", url: "black-crows-atris#image=138838/569533/black-crows-atris-skis-2019-178.jpg")
Ski.create!(name: "Nordica Enforcer 110", description: "The Nordica Enforcer 110 is a master of the mountain. Groomers? It carves ’em like a butcher.
 Crud? It eats it for breakfast. Powder? It floats it like a dream. “The essence of fluidity, so smooth from edge to edge,” commented FREESKIER publisher Damian Quigley.
  “One of my all-time favorites; it’s stable, playful, surfy and fun,” added tester Drew Ingardia. Nordica sandwiches a versatile poplar, beech and balsa wood core between two layers of Titanal and a carbon prepreg laminate for a ski that’s smooth in all facets of the game.
  Its rocker-camber-rocker profile makes this race car a dream to handle, too.", brand: "Nordica", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Enforcer110.png", category: "Powder", price: "899", url: "nordica-enforcer-110#image=138870/572918/nordica-enforcer-110-skis-2019-169.jpg")
Ski.create!(name: "Völkl M5 Mantra", description: "The Mantra has been an icon in the all-mountain world since 2005-06.
 The fifth generation Mantra, dubbed the M5, is set to do the same but with a new construction strategy.
  Völkl arranges Titanal around the perimeters of the tip and tail, while also utilizing a carbon inlay in the nose.
   This decreases the ski’s weight without losing the damp, stiff properties that a full sheet of metal provides.
    The Volkl M5 Mantra also features a rocker-camber-rocker profile, allowing it to perform in any situation.
     Justin Greene’s review says it all: “Has absolutely no speed limit on hardpack, cuts through the crud as if it’s not there, is nimble through the bumps and has so much life to it.", brand: "Völkl", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/M5Mantra.png", category: "All-Mountain", price: "825", url: "volkl-m5-mantra#image=133989/579492/volkl-m5-mantra-skis-2019-177.jpg")
Ski.create!(name: "Völkl 90Eight", description: "The Völkl 90Eight is hot… much like that Nick Lachey-led ’90s boy band with a similar name, only way better. The perennial Editors’ Pick utilizes a poplar and ash wood core that provides a mix of rigidity, stability and energy, along with carbon stringers for a touch of torsional stiffness.
 In addition, Völkl implements multiple layers of folded glass in the binding area to improve responsiveness and power transmission to the edges.
  The end result is a ski that can charge with the best of ’em and isn’t a slouch in the playfulness department, either.
  “These carved trenches around the entire hill,” commented Thomas Lampert. “They were also fun to pop off side hits and ride the tails.” Like we said, these cats are hot.", brand: "Völkl", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/90Eight.png", category: "All-Mountain", price: "775", url: "volkl-90eight")
Ski.create!(name: "Völkl Confession Skis", description: "The choice of spine-slaying, big-mountain rider Ian McIntosh, Völkl’s Confession skis are a set of powerful, directional pow slayers, light enough to play with yet sturdy enough to get you down the steepest high-alpine faces with confidence.
 Utilizing a beech and poplar wood core ensures a sturdy base, while a Titanal band and carbon stringers run through the center of the ski to further increase its strength without adding weight.
 The Confession’s rocker-camber-rocker profile allows you to carve an edge just as well as smear a turn. “Insane ski. Carve the sh#t out of it or attack the crud. Really impressed with the overall performance of this ski,” commented tester Willie Ford.",
 brand: "Völkl", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Confession.png", category: "Powder", price: "875", url: "volkl-confession#image=140489/572889/volkl-confession-skis-2019-179.jpg")
Ski.create!(name: "Armada Tracer 118", description: "Armada’s Tracer 118 is designed for the skier who is continually seeking the next high-altitude objective and wants a pair of skis that can handle a multitude of snow conditions. Significant rocker in the tip as well as slight tail rocker keep the Tracer nimble, while camber underfoot ensures great snow contact.
 Inside the ski, you’ll find a combination of poplar and ash wood in the core reinforced by a layer of woven fiberglass and two strips of Titanal.
 The result is a reliable ski that holds up on the steepest of descents, while optimizing flex and maneuverability. According to Donny O’Neill, this ski is “more energetic than a gaggle of puppies. Lightweight yet stable; rails turns but is still nimble in trees and bumpy terrain.”",
 brand: "Armada", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Tracer118.png", category: "Powder", price: "950", url: "armada-tracer-118-chx#image=140312/580390/clone.jpg")
Ski.create!(name: "Salomon QST 118", description: "“Light, light, light like a feather,” said Steve Karczewski. “Take this playful, strong ski anywhere you dream,” noted Sam Taggart.
 Adrian Bouthot commented that these planks “hug the snow and provide a magic-carpet-like feel. Can and will pop at a moment’s notice and make slalom turns on a dime.”
 The widest of the QST series, the 118 is a true big-mountain powerhouse, with a fully rockered tip and tail to plow through variable snow conditions, a woven layer of carbon and flax that provides the strength of metal without sacrificing weight, a five-point sidecut for extra maneuverability and a Koroyd insert in the tip and tail for chatter reduction when you’re nuking.",
 brand: "Salomon", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/QST118.png", category: "Powder", price: "900", url: "salomon-qst-118#image=139106/573954/salomon-qst-118-skis-2019-171.jpg")
Ski.create!(name: "K2 Catamaran Skis", description: "When you have the minds of legends like Pep Fujas and Sean Pettit helping to create a ski, you know that 1) It’s meant to surf the deepest of the deep, and 2) It’s playful “AF.”
 Don’t believe us? Take it from tester Adrian Bouthot, “You can feel Pep and Pettit’s influence on these bad boys. They pop, slash and tap better than most at this size.
 It’s also super stable and provides an amazing landing platform.” To reflect Pep and Pettit’s sensibilities, K2 employed an asymmetrical shape, an elongated taper on the outside edge, which shortens the uphill ski’s effective edge, allowing for seamless butters and slashes. The ski is also built with denser fir wood over the edges for strength and aspen with carbon stringers down the center to increase liveliness.",
 brand: "K2", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Catamaran.png", category: "Powder", price: "850", url: "k2-catamaran#image=138345/570621/k2-catamaran-skis-2019-177.jpg")
Ski.create!(name: "Armada Edollo Skis", description: "At the forefront of freestyle skiing, Henrik Harlaut’s signature twigs are back on shelves heading into 2019.
 Dubbed the Edollo, these skis are “so buttery, I felt my arteries clogging,” explained Russell Wontor. That’s no surprise given their namesake’s signature style of skiing.
 A wider, 98 mm platform, updated flex pattern with a softer tail and ultra-thick steel edges and base construction make these skis durable, playful, poppy and sturdy, simultaneously. All in all, these are a pair of “butterlicious skis that want to be pressed hard and often, and can still hang on the groomers,” said veteran tester Adrian Bouthot.",
 brand: "Armada", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/Edollo.png", category: "Park", price: "700", url: "armada-edollo#image=140332/580357/armada-edollo-skis-2019-164.jpg")
Ski.create!(name: "Line Tom Wallisch Pro", description: "One of the biggest names in the history of skiing, Tom Wallisch knows what he wants out of his skis: a durable, relatively stiff yet playful set of boards to stand up to the longest urban kink rails and the biggest terrain park features.
 “I really like the flex on this ski, and the way it skis through rails… a reliable ski from Line,” noted park tester Aidan Sheahan. “Great stiffness for hitting jumps but still playful on the rails,” said Sam Zahner. The latest TW Pro features a symmetrical flex pattern for simple switch skiing, a five-point radius for easy carving and effortless maneuvers and a wood core consisting of two full-length maple stringers surrounded by aspen for increased strength and durability.",
 brand: "Line", photo_url: "https://s22867.pcdn.co/wp-content/uploads/2018/09/WallischPro.png", category: "Park", price: "550", url: "line-tom-wallisch-pro#image=138265/567857/clone.jpg")
# Ski.create!(name: "", description: "", brand: "", photo_url: "", category: "", price: "", url: "")


 puts 'creating articles ..'
Article.create!(title: "Tof Henry Is The Fastest Skier in Chamonix", subtitle: "He straightlines the Alps’ steepest slopes, yet a turbulent life off the hill might be exacerbating his extreme style.",
 main_article: " Daniel Rönnbäck was standing in the tramline of Chamonix's Aiguille du Midi with the late Andreas Fransson when he first saw Christophe 'Tof' Henry. It was 2012 and Fransson nodded toward the third-generation Chamoniard, whose black mop of hair wisped across his tanned cheeks, and said to Rönnbäck, 'That kid is the next generation of steep skiing. He's the fastest skier in Chamonix.'
But you wouldn't need a steep skiing legend like Fransson whispering in your ear to notice Henry's swagger. The way he cuts to the front of the tramline with baggy bibs hanging off his broad 6-foot-3-inch frame resembles a high school basketball star waltzing in late to class.
 Or perhaps you've seen POV videos of him straightlining sheets of blue ice on 50-degree test-piece lines before launching onto variable snow and cranking GS turns on an exposed hanging glacier.
 Around the Chamonix Valley, where he has lived for all of his 33 years, Henry is known to skip entrance rappels above classic lines like the narrow Col du Plan couloir or the highly coveted Mallory-Porter, a route that plunges 5,000 vertical feet below the Aiguille du Midi cable car. He skis no-fall zones like he's freeriding inbounds and does so on high avalanche days in bad weather with low visibility.
  And just in case you're unsure if Henry is a big deal, he's ready to let you know. 'I ski top of Mallory in May last year with nine turns,' he says loud enough for anyone on the street to hear it. 'No fucking hop turns!'
  Elevation 1904 bar just off Chamonix's main square on an April afternoon in baggy jeans and two hoodies, Henry was drinking like he skis—fast and without hesitation. I asked if he ever brings a guide along to handle his photographers or film crews. 'I don't need a guide,' he says. 'I'm better than guide. They ask me where is the good snow.'
 When pressed on what he's trying to accomplish in his ski career, it might be the easiest question he's ever answered. 'My goal is to ski all the hugest lines you can in Cham in different way and style: fast and big,'he says, his thumping pulse visible in his jugular vein.
 Despite all of the impassioned chest beating, his connection to the peaks is a source of vitality that calls him on a near-daily pilgrimage. Skirting the thin line between dialed and loose is precisely where Henry feels centered and free. Yet down on the valley floor, his world is weighted with personal woes and an unsettled family dynamic threatening to knock him off-balance.
 After an hour or two of throwing back beers, recounting his favorite ski lines and dreaming of summer van-life to ski first descents in the Chilean Andes, Henry spotted a blonde rascal with a red bandana around his neck running by on the sidewalk. 'Jules!' Henry called out to his 6-year-old son, who kept on running, babysitter in tow. When the boy passed again, Henry swooped the kicking child up into his lap.
 The boy squirmed out of his grasp and ran off. For the first time all day, Henry's enduring smile gave way to a troubled face. 'Sometimes he doesn't want to spend time,' he says softly with a long, sad drag on his cigarette.",
 second_article: "Henry grew up skiing from the age of 2 in Chamonix. His parents were working-class weekend warriors at best, not deeply embedded in the mountain culture so often romanticized in the birthplace of alpinism. He had an unremarkable childhood and a subdued personality until he was 15. That's when he started skiing with fellow Chamoniard Aurélien Ducroz, an eventual two-time Freeride World Champion skier.

'We would freeride together, learning how to use the big wide ski,' Henry says. 'This was the new revolution.' Having such unmatched access to big vertical and long seasons breeds rapid progression in Chamonix, if the motivation is there. And it was, so much so that Henry was too busy skiing to finish high school. By age 20, he was skiing faster than most locals on open freeride terrain, working as a ski instructor and finding summer labor jobs clearing trees and building a zip line and ropes courses—anything to keep him outdoors.

In 2014, tragedy struck the Henry family, when his mother, Francoise, died of leukemia. Soon thereafter, a Christmas dinner ended early after an argument erupted between Henry and his father. The two have not spoken or seen each other since. That left just a few close friends at his wedding in April 2016. A little more than a year later, Henry's wife took Jules, who they had when she was 22 and Henry was 27, and left, for the second time, with another man. Henry, meanwhile, was skiing in Chile for two months. That July, he posted a video on Instagram of him skiing a couloir barely wide enough for his skis with the caption: [sic] 'No more mum no more dad no more love from my wife, missing my son, fortunatly the passion is here and save me…'

When he returned home to face the music last September, he was a wreck, living out of his 2005 Volkswagen Transporter van piled with 25 pairs of skis, and only seeing Jules once a week. His younger sister, Caroline, who had the hard task of breaking the news to Henry about his wife's 'extra conjugal man,' was worried about him. 'Tof wanted to stay at the bar and drink, and I was worried if he'd go to the mountain and maybe not worry about the risk as much,
' she says as smoke ribbons swirl from her cigarette on the patio of the Chamonix café where she works one of two jobs. 'He thinks he knows everything, but Mother Nature is stronger than him and I am scared that sometimes he forget it. But I know when he feels bad, the skiing and the mountains are his medicine, his therapy.'

Indeed, the day after they buried their mother in the same Chamonix cemetery where centuries of legendary alpinists lay, Henry was skiing off the Midi. But when Henry talks about skiing, it sounds more like a drug than therapy. 'I'm so stoked in the mountains, I always want more,' he says. 'It make you crazy. I get down and I just want more, more, more.'",
 writer: "Powder Magazine", photo_url: "https://cdn.powder.com/uploads/2018/09/powp-181000-prof-05-640x427.jpg", photo: "https://cdn.powder.com/uploads/2018/09/powp-181000-prof-07-640x480.jpg", second_photo: "https://www.freeride.se/jacobwester/wp-content/uploads/2014/03/com2014_Photo_danielronnback_0016_4994-590x392.jpg")
Article.create!(title: "Stay High", subtitle: "Executive Editor Matt Hansen's introduction to the October Issue of Volume 47
", main_article: "For several years, there was a traverse at Bridger Bowl, Montana, that tied me in knots. After a couple hundred feet of manageable dips and doodles on the north end of the Ridge, the traverse took a hard left turn between the vertical mountainside and a 50-foot cliff.
 Making matters worse was a stubborn old pine tree, about 15 feet tall and 5 inches in diameter, that stood right at the crux. Over the years, the tree's branches had been snapped off by skiers who used it as an oh-shit handle. But the trunk wasn't quite smooth enough for you to whisk by without worrying it might snag a pack strap or rip your jacket and send you tumbling down over the rocks.
 I hated that tree. I hated that traverse. I hated my brother, a Bridger local, for taking me on it. But there was always a choice: Take the easy way down, or see what's on the other side.
One of the beautiful elements of skiing is that it presents us with choices every day. Most decisions are small—daffy or spraffy?—with consequences that might tweak your knee but won't end your life. Others walk the line between a life well-lived—dawn patrol after a storm?—and the dark matter that means you better have your systems dialed. It's often hard to tell which is which until you are squared up against the moment, eyes wide as you stare down your own mortality.
In a lot of cases, the difference comes down to a simple left or right turn: left goes to a groomer, the base area, and hot cocoa. Right means you stay high. Nowhere is this more apparent than at backcountry gates and traverses, where the weight of that left-or-right decision typically comes to the fore right about the time you need a new pair of undershorts. Which is to say, we often don't appreciate the decision until it's too late.
I've made that choice to stay high on countless occasions, and questioned my decision-making many times. Maybe my pack felt too heavy, or my hat was too soaked with sweat. Other times it was fatigue, or the time of day, or too much chili for lunch. All those times at Jackson Hole, Big Sky, and Alta where rocky, rutted-out goat paths were necessary evils consisting of the worst snow imaginable. Or that one time in La Clusaz, France, where I had to leap over a failed snow bridge and landed awkwardly on my ice ax, with the tip puncturing my jacket but luckily nothing else.
But that one Bridger traverse got to me every time. I could always see myself getting hung up on the tree before falling over the cliff. My brother typically made it look easy, while I stood paralyzed thinking of my own demise.<br> Just below my skis was a clear path to avoid the nonsense altogether. Many people had already made that decision, evidenced by the chopped-up mank they'd left behind, bypassing the tree and the cliff and the associated anxiety.",
 second_article: "It's never fun to be scared, but we do risky things in order to achieve a certain goal: be it a thirst for an untracked patch of powder; the challenge; or, quite honestly, to vividly experience a vertical world of snow, rocks, and gnarly trees that grow in the most impossible places.
So after a minute of contemplation, I'd exhale, slowly ski up to the tree, grab a hold of it, and pause for a beat to look over the cliff, just to make sure it was still there. Then I'd let go and ski safely to the other side.
With the knot of the traverse successfully untied, I'd arrive at the top of a field of powder and give my brother a high five. Finally, the easy way down.
This story originally appeared in the October 2018 (47.2) issue of POWDER. To have great stories like this delivered right to your door, in print, ",
 writer: "Matt Hansen", photo_url: "https://farm1.nzstatic.com/_proxy/imageproxy_1y/serve/whakapapa-ski-area.jpg?focalpointx=51&focalpointy=40&height=427&outputformat=jpg&quality=85&source=4225030&transformationsystem=focalpointcrop&width=640&securitytoken=3470D6FF6019DB132CC0C1A25C166A59", photo: "https://image.jimcdn.com/app/cms/image/transf/none/path/s5ca6bf58cd6d87f2/image/i74d053e73f92ac95/version/1539353194/image.jpg", second_photo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlY2gVBoQy9Its0Ww_l7VM2-JpY017qxHpRGbRB5MEvOreh77s")
Article.create!(title: "The Making of a Ski Town", subtitle: "As Revelstoke Mountain Resort enters its second decade, local legend Greg Hill opens up about how the resort has changed his town",
 main_article: "Back in the winter of 2007, a bomb dropped on the peaceful town of Revelstoke, B.C., and more specifically its diminutive ski hill then known as Powder Springs. Plaid-wearing, hard-working Revelstoke locals put down their snow shovels in unison, momentarily gazing skyward to a brand-new mega-resort rising above their ever-growing snowbanks.
Greg Hill was among them, fresh from becoming the first skier to tour a million vertical feet in a season. He was likely the only person in his neighborhood whose yard chores didn't follow a shift at the nearby hydro dam, railyard, or lumber mill.
A decade later, as Canada's undisputed backcountry skiing ambassador, Hill might be expected to be waist deep in nostalgia about the changes that Revelstoke Mountain Resort (RMR) has imparted on his small-town lifestyle.
After all, what was once the exclusive playground of like-minded touring folk and a few heli-skiers has morphed into something as unrecognizable as his woodshed buried under a giant snowdrift.
Is the true soul of Revelstoke—or Revy, as it's now known—still in there somewhere?
When queried about RMR going into its second decade, the father of two displays exactly the opposite sentiment one might expect about Revy's changes. 'Quite simply, it has brought the mountain soul back to Revelstoke,' says the ever-positive Hill.
'Our town's' identity has gone from a town with no real vibe to a bustling mountain community with endless potential.'
Indeed. No longer just a pit-stop along the TransCanada Highway, Revy has grown to become a must-see, must-ski, must-live-here destination for serious skiers the world over. Drop into the après scene at The Village Idiot to hear a post–powder day symphony of foreign accents and languages.
What's lacking now is the redneck drawl of yesteryear, bar brawls, and grubby roadside fare.",
  second_article: "Ski bums of all kinds are drawn in. RMR employs roughly 500 people in a given winter, which further contributes to the town's booming economy. Most of the pull comes from RMR's impressive resumé: Boasting the highest vertical of any resort in North America (5620 feet) and being a stone's throw from the site of Canada's record-setting snowfall (80 feet, back in 1972), this mountain is the real deal. Located smack in the middle of the legendary Selkirk Range, RMR's towering Mount Mackenzie maxes out on both terrain and snow quality. This is affirmed by anyone who's ever dropped into a pillow line on the hill's trademark under-the-gondola run, Kill the Banker. These assets are, according to Hill, but a jewel in the town's well-adorned crown.
While you might see 'Two-mil Hill' (Greg later skied 2 million feet in a year) skiing with his kids, smashing gondo laps or ripping Snow Rodeo—a 5,000-foot groomer on RMR's front side—he does, of course, still adhere to his roots, sauntering along on his so-called 'two-hour adventure.' That's two hours, car-to-car, from coffee shop to the top of The Stoke chair, touring to Mackenzie's summit, then back down via either Brown Shorts or Thumbs Up—two of myriads of rowdy out-of-bounds options.
 Just like he's always done.",
 writer: "Powder Magazine", photo_url: "https://cdn.adventuresportsnetwork.com/uploads/2018/10/revelstoke-jj-dropin-colour_ian_houghton-1.jpg", photo: "https://static.evo.com/content/travel-guides/bc/revelstoke/royce_sihlis_1.jpg", second_photo: "https://d50gait2982zr.cloudfront.net/wp-content/uploads/2017/10/plan-your-vacation-04.jpg")
Article.create!(title: "Fernie’s Fire", subtitle: "Home isn’t always where you grew up. For us skiers, it’s the place that ignited our passion.",
 main_article: "Before 1997, the only ski resort in southeastern B.C.'s Lizard Range was named Fernie Snow Valley.
  It was an apt name for a place buried in powder for almost six months of the year. When I first arrived in October of that season, lazy legs had already zigzagged long, slow skin trails across water bars and barely concealed grass to the top of the tree line.
  I followed them. Fresh out of high school, with unrestrained joy and a sweaty brow, I believed I had discovered Utopia.
  Impossibly light snow seemed to part before my tips, blown wistfully aside with each impatient teenage turn, or by the hand of Ullr. Indeed, that first November we gathered around a bonfire to sacrifice P-Tex and weed to the god of snow during the annual Mogulsmoker, once one of Fernie's most sacred ceremonies.
  The fires we light die to embers as we grow older, but embers can still ignite. For me, this town's coals still glow.
  Fernie in the '90s was a burgeoning ski community. Hardly known outside of British Columbia and Alberta, this tiny coal powerhouse in the Elk Valley was beginning a decade-long transition from resource town to ski destination. It was a time of change. Sometimes it was fearsome, sometimes fascinating. The snow fell constantly. The people were friendly. It was a place a powder skier could grow with. Less than a month later, the ski resort opened with a new owner and new name.
  I began a job at the newly-christened Fernie Alpine Resort that would change my life. I became a liftie.
  The Bear T-Bar was the only permanent lift to take skiers to the resort's high point. It was a treacherous and often icy zipper placed in the middle of an apron of protected powder. Informally, it is called The Triangle. From the plateaued off-ramp of the T-bar, most skiers went left towards Arrow and Bow, two alphabetical undulating pitches that meandered through trees and over cat tracks. But perhaps the most sought after first run off the Bear was Sunnyside, a steep, short, and joyous pitch on the side of the T-bar track. It was a classic Hollywood line with generous room for big air and bigger mistakes. These few runs were the first to open on a big powder day, and they were accessed exclusively by the Bear T-Bar. I was one of four lifties that pulled tees on that lift. Every day, when our coffee break arrived, I swapped out boots and skied as hard as possible, lapping Sunnyside quickly in hopes of impressing my supervisor enough that he would let me take another. And another. While others smoked cigarettes shamefully behind the lift hut, I inhaled face shot after face shot of pure Kootenay powder.
  CHANGE IS A CONSTANT, and I left Fernie after one season, lured away by summer employment and companionship after a long winter of lonely, lovely skiing.
  But I would soon return. Fired from a job on Alberta's oil fields, I gravitated back to the only place that felt like home. I was hired as a liftie again, this time as a supervisor. I gave ski breaks to those who skied hardest. Smokers continued to suffer.
  Like Utah or Hokkaido, Fernie was and is all about powder. Long traverses weed out the lazy, impatient, and snowboarders. Only dedicated skiers are left to access the steep, fresh fall lines on Snake Ridge, in Easter Bowl, and off Stag Leap.
  It is the patient and the quick who benefit most. While the peaks that provide the backdrop above show up most in photos, this is a ski resort defined by open bowls and the ridges that divide them.",
  second_article: "Collectively, I spent a decade exploring these aesthetic contours. Reveling in them. Losing friends in them. Making mistakes in their many hidden corners and learning how to handle the subsequent consequences as I grew alongside both the town and the mountain.
  And then I left, yet again. To become a writer. To attend school. To chase a career. To foster relationships. To find a social scene outside the sometimes-suffocating ski-town sphere. But I always return to steal Fernie's riches away from her steep slopes, and to tell her story. Over almost two decades—in bars, photos, and magazines alike—I've told the tale of Fernie as both long-time local and giddy tourist, as blind supporter and well-meaning critic, as an old partner who misses his muse, and as a relieved lover who finds her pure adventurous spirit untainted after all these years. She is beautiful. She is timeless.
  IN 2016, I MOVED TO AMERICA. Blinded by the halcyon promise of southern California's polished dream, I surfed poorly and ate too many fish tacos and wrote about other people skiing in exciting places. Far from snow, my ski roots became brittle. I did not last long before conceding defeat, beaten by building debt and boredom. I decided to return to Canada.
  'Where to?' was not a question that required answering.
  With no job and nowhere to go, I did what every lost child does—I returned home. I pointed the truck north in November, through Northern California's dense maritime snowpack and Oregon's torrential rains, and the Canadian border welcomed me home as only a homeland can.
  The welcome in Fernie was even kinder.
  I arrived to a classic Fernie storm. Sixteen inches fell over three days, and no one but locals were around to ski the early season bounty. I unloaded the chairlift and, instead of turning left, as I always did during cold-smoke breaks so many years ago, I went right, into Cedar Bowl. With weak legs and temperature-sensitive skin, I let gravity pull me back into Fernie Alpine Resort's deep, frigid embrace. Overcome by both inertia and emotion, my voice was unleashed, reverberating through those widely-placed trees, an exhalation of all that had buried me. An invitation to become acquainted again with an old friend.
  THE NEXT SUMMER, my wife and I watched our former neighbourhood burn to the ground on television, as Southern California experienced the worst wildfires in their history. As the Santa Ana winds whipped flames into a frenzy that tore hot and fearsome through Ventura and Ojai, we gave thanks for the northern wind that carried us home, and for the charming ski resort that welcomed us back with alabaster grace and the allure of infinite turns in the white room of the Lizard Range.
  I was lucky enough to find my fire early. Like many of you, skiing has played the role of guiding star, even when I ignored her nudges. In the end, though, it was the special iridescence of this place that flickered and flamed, and Fernie was the light that guided me home.",
  writer: "Powder Magazine", photo_url: "https://www.snowmagazine.com/media/reviews/photos/original/c9/bd/d4/fernie-resort-53-1386935442.jpg", photo: "https://img4.onthesnow.com/image/gg/37/378177.jpg", second_photo: "https://skinakiska.com/wp-content/uploads/2016/09/Fernie-H-G.jpg")
# Article.create!(title: "", subtitle: "", main_article: "", second_article: "", writer: "", photo_url: "", photo: "", second_photo: "")
 puts 'resort created..'

 Resort.create!(name: "Aspen Snowmass", address: "610 S. West End Street, Aspen, Colorado", description: "Aspen Snowmass has many draws; celebrities have second, or third, homes here, ski and snowboard bums come for the snow, and visitors come for this combination of luxury and deep powder. Aspen is one of the most well known Colorado ski and snowboard destinations in the world for these among many other reasons, including its long and storied ski history. With four separate ski and snowboard areas, there is an amazing selection of terrain, for movie stars and powder hounds alike. In total, Aspen Mountain, Snowmass, Buttermilk, and Aspen Highlands make up over 5,500 acres of skiable terrain. Amongst all of this terrain is some of the best skiing and snowboarding in Colorado.The town of Aspen is a destination in itself for many who prefer to sample the upscale shopping and dining rather than spend their time on the slopes.
The variety of terrain is enough to keep skiers and snowboarders of any ability busy for days, making Aspen Snowmass a great destination for longer trips. It’s location in the Roaring Fork Valley, about three and a half hours from Denver, keeps away the crowds that often plague other Colorado ski and snowboard areas.
Aspen Mountain:
Aspen Mountain’s eight lifts rise straight out of the town of Aspen. These chairlifts and one gondola serve intermediate and advanced terrain only, with lots of great glades to explore. The ski area is rather narrow from side to side, with most of the best terrain located on the sides of the ridges, like the steep glades off of the Ridge of Bell under the gondola. Farther out on the peripheries, skiers and snowboarders can find powder stashes left long after snowstorms. Check out the terrain off of Gentleman's Ridge and Traynor’s Ridge. At 675 skiable acres Aspen Mountain is quite small, only a fifth of the size of Snowmass.

</strong>Snowmass:</strong>
With over 150 miles of trails and 4,400' vertical, Snowmass claims “you can spend your entire trip skiing and riding its terrain without covering the same ground twice.” The huge mountain has some of the best beginner skiing and snowboarding in Colorado, as well as some of the best powder terrain in Aspen. The entire lower mountain is dedicated to beginners and intermediates. This is awesome for those skiers and snowboarders who are just learning, but still want to explore. The Powerline Glades are widely spaced, and a nice option for intermediates looking to venture off piste and get a taste of powder riding. Up on the High Alpine and Cirque lifts there are plenty of options and powder stashes for advanced and expert skiers and snowboarders to explore. Powder lasts the longest far to the skier’s right of the mountain in the Burnt Mountain Glades.

Buttermilk:
Buttermilk’s 470 acres make it the smallest of the Aspen ski and snowboard areas, however, it is a great area for beginners, and has some of the best terrain parks in the world. The West Buttermilk Express chair has great learning terrain that is sparsely crowded. Meanwhile the terrain parks are some of the biggest and best in Colorado. Each year in late January Buttermilk’s terrain parks play host to the X Games slopestyle and halfpipe events. There are also plenty of smaller features for those skiers and snowboarders that are not ready to send it like Tom Wallisch and Sage Kotsenburg.

Aspen Highlands:
While there is beginner and intermediate terrain at Aspen Highlands, the ski and snowboard area is known for steep and deep expert terrain. The infamous Highlands Bowl sits atop the the ski area, offering pitches as steep as 48 degrees in the huge alpine bowl. After a free snowcat ride a short ways up, skiers and snowboarder can hike the additional 780 vertical to the top of the bowl. The hike takes anywhere from 10 to 60 minutes depending on fitness level. At the 12,392 foot summit, skiers and snowboarders can catch views of the Maroon Bells peaks, while contemplating which line to descend. Highlands Bowl is an Aspen right of passage, and a can’t miss for advanced skiers and snowboarders. The steep trees of Loge Peak and Deep Temerity lifts offer more options without hiking, and for lower visibility conditions.",
 photo1: "http://informedenieve.com/wp-content/uploads/2017/09/1-1.jpg", photo2: "https://images.inntopia.com/photos/1650700/1650700-116.jpg", photo3: "https://img4.onthesnow.com/image/gg/14/1_144129.jpg",
  trail: "https://www.skibutlers.com/blob/image/L3ZXVWVMRi9yZE090", region: "Colorado", tips: "The four ski areas of Aspen Snowmass receive between 300” and 350” of annual snowfall. This makes for plenty of powder days throughout the season. Colorado is a great ski and snowboard destination because of the combination of snowfall and plenty of sunshine.
  Conditions can change quick however, especially high in the alpine terrain of Aspen Highlands and Snowmass.")
 Resort.create!(name: "Snowbird", address: "Holladay Cottonwood, Utah 84092, EE. UU", description: "Snowbird has some of the best inbounds terrain in Utah and the United States as a whole. The expert terrain here is steep, deep, and has lines that even challenge the many professionals who are frequent guests at the Little Cottonwood Canyon ski and snowboard area.
  Huge snowstorms drop tons of powder on the resort all winter long, the terrain is like a playground, and Snowbird is only 35 minutes from Salt Lake City; it’s hard to dream up a better combination.
  There are three main parts of Snowbird, Peruvian Gulch, Gad Valley, and the backside Mineral Basin. The famous Aerial Tram and Peruvian Express lifts service Peruvian Gulch, the skier’s right side of the mountain, which borders neighboring Alta. The Baldy Traverse to skiers right, and Cirque Traverse to the skier’s left access many Snowbird classics, and some of the gnarly terrain that the ski and snowboard area is known for. There is a huge variety of lines in this area, tons of steep and tight chutes, as well as plenty of cliffs. The Cirque Traverse first passes a handful of tight, rocky chutes with names like the Death Chutes and Forbidden Zone. Farther down the traverse things open back up into the more manageable and open Middle Cirque and Lower Cirque. Continuing past these runs, there are more chutes to either side of the ridge.
  From the top of the Peruvian lift, a magic carpet conveyor lift goes through a tunnel delivering skiers and snowboarders to Mineral Basin. This Disneyland-esque experience accesses some more of Snowbird’s great terrain. Located on the sunny southern side of Snowbird’s peaks, Mineral basin has more fun chutes, wide open bowls, and cliffs.
  The Little Cloud and Gad 2 lifts over on the Gad Valley side of the mountain are fun alternatives to Peruvian and Mineral basin when lift lines are longer.
  The locals are a dedicated and hard shredding bunch, but fresh powder lasts a bit longer on the far reaches of Gad Valley towards the ski area boundary. While a lot of Snowbird’s terrain is lacking in trees, the Bird’s best tree skiing and snowboarding can be found over here.
  The majority of the beginner and intermediate terrain at snowbird is over on this part of the mountain The Baby Thunder Lift serves the beginner learning are, while Gadzoom and Gad 2 are the gateway to the intermediate terrain.", photo1: "https://img1.onthesnow.com/image/xl/91/snowbird_athlete_ben_wheeler_skis_tram_1_91422.jpg", photo2: "https://www.skibacs.org/media/com_eventbooking/images/snowbird_tram.JPG", photo3: "https://www.tetongravity.com/images/ci-images/kickapps/PHOTO_15386278_75233_34540729_ap.jpg",
  trail: "https://res.cloudinary.com/liftopia/image/upload/c_fit,d_defaults:default_logo_1.png,f_auto,h_980,q_auto,w_980/v1/production/trail_maps/b45d084c2ad69658a44a359e1f950913.jpg", region: "Utah", tips: "Snowbird receives a crazy 500” of average annual snowfall. The quality of snow here is amazing, too, falling light and deep. A lot of the terrain at Snowbird faces north, which means it sees little sun during the winter. This keeps the powder fresh for as long as it takes to get skied out. Mineral Basin faces south, getting baked in the sun. This can turn powder into heavy “mashed potatoes” quality snow, or soften up crud to make great spring corn snow. The exposed and treeless terrain can get windy and very cold throughout the winter, so make sure to check out the conditions and prepare accordingly.
  Snowbird is located on mainly private land which enables the ski and snowboard area to stay open as long as they have snow, which can be deep in the spring and even into the summer.")
 Resort.create!(name: "Park City", address: "1345 Lowell Ave, Park City, UT 84060, EE. UU.", description: "Located just a 35 minute drive from Salt Lake City, Park City is one of America’s largest ski and snowboard areas. In the summer of 2015 Park City undertook a massive infrastructure project linking Park City with Canyons ski and snowboard area. As a result, Park City now has over 7,300 skiable acres.
  These mountains have something for everyone, including some of the best terrain parks in Utah.
  The town of Park City is a nice mountain town, too, making Park City a great skiing and snowboarding destination resort.
  Park City Side:
  Skiers and snowboarders can start their day from the historic downtown Park City on the Town Lift, or at the main base with the Payday and Crescent lifts. The lower mountain, off of these base chairlifts, is great for families because of the variety of terrain. There is something for every level for beginner to advanced. Intermediate skiers will love the King Con lift, and the huge choice of runs it serves.
  Park City is well known for its terrain parks. Both the skiing and snowboarding men’s slopestyle 2014 olympic gold medalists, Joss Christensen and Sage Kotsenburg, call the mountain home. These parks are located close to the base of the mountain off of the Three Kings lift. Park riders of all levels will find fun features that are changed up constantly throughout the winter.
  While Park City isn’t as well known for having steep expert terrain, powder hounds can still find some fun skiing and snowboarding high up off of the Jupiter and McConkey’s lifts. Off of Jupiter, there are lots of glades and chutes to explore. These runs offer some of the best powder skiing and snowboarding at Park City. A traverse and a quick hike accesses Jupiter Peak, which holds fresh powder for a little bit longer after snowstorms. To the skier’s left of the Jupiter chair, the ridge that separates the Park City Base from the Canyons Base has more fun tree and glade skiing.
  Canyons Base:
  The Quicksilver Gondola connects the Park City to the Canyons Base, which used to be its own separate ski and snowboard area. Similar to the Park City side, The Canyons side of the mountain has a huge variety of intermediate terrain.
  Advanced and expert skiers and snowboarders will want to head to the Ninety-nine 90 lift, and the Super Condor lift to get to the steepest and most challenging riding.
  The riding on Murdoch Peak, off the Super Condor, there is a great selection of tree skiing and snowboarding, as well as plenty of challenging moguls. The short hike to Murdoch bowl s a good spot to head for fresh powder.", photo1: "https://static.evo.com/content/travel-guides/utah/park-city/town-2.jpg",
  photo2: "https://s3.amazonaws.com/fathom_media/photos/snowbird-main.jpg.1200x800_q85_crop.jpg", photo3: "https://www.skimag.com/.image/t_share/MTQ0NDE2MzgxMjQ3NTYzNDE4/ski1116_go_pcmr6jpg.jpg", trail: "https://static.evo.com/content/travel-guides/utah/park-city/parkcity_trailmap.jpg", region: "Utah", tips: "Park City Mountain averages 360” of annual snowfall, which is a little bit less than the ski and snowboard areas in the Big and Little Cottonwood Canyons: Alta, Snowbird, Brighton and Solitude. That is not to say there isn’t a lot of powder to be found at Park City, there are plenty of deep days throughout the winter. Springtime is great at Park City, too.
  Sunshine and slush make the terrain parks a ton of fun as well as the whole mountain.")
 Resort.create!(name: "Vail", address: "292 E Meadow Dr, Vail, CO 81657, EE. UU.", description: "Vail is one of the top ski and snowboard destination in Colorado and the United States as a whole. Known for extreme luxury and the vast terrain of the Back Bowls, Vail certainly has a lot to offer. With three base areas and a vast network of chairlifts, it’s easy to feel overwhelmed. With some basic knowledge of the mountain, however, the 5,289 acre ski and snowboard area can feel like your home mountain.
  All of this amazing skiing and snowboarding can be found only a two hour drive from Denver.
  The key to having a great time skiing and snowboarding at Vail is to not spend too much time traversing the mountain trying to get from one side to another. The mountain is huge, so it’s easy to waste time on catwalks. Vail has three base areas. From skier’s left to skier’s right, they are Lionshead, Vail Village, and Golden Peak. All three are interconnected, and each have different strengths. The free in-town busses connect each base, too, so it's easy to get from one to another. The variety of the terrain makes for plenty of skiing and snowboarding for all ability levels, from beginner to expert. The legendary Back Bowls are made up of primarily advanced terrain, however there are some intermediate and beginner options. Given the large size of the ski and snowboard resort, there are lots of hidden powder stashes and less busy areas to explore.
  The Lionshead Gondola is a great place to start out a day at Vail. From the top there are a handful of beginner and intermediate runs that lead to Chair 2. Chair 2 has more nice groomed runs, and also accesses Game Creek Bowl. Game Creek is fun place to head first on a powder day, it’s one of the most accessible back bowls, and therefore can get very crowded. A ride up the Game Creek Chair 7, skiers and snowboarders have the chance to experience the true heart of the Back Bowls. Sun Down Bowl has some great open pitches, and great skiing and snowboarding on a powder day, or in spring slush. Chair 5 brings skiers and snowboarders back to Buffalo’s Lodge, which is accessed by three different chairlifts.
  From here, there are many options, including heading to the groomed runs off of Mid-Vail’s Chair 3 and 4, heading to the fun mix of groomers and glades off of Chair 11, or heading deep into the Back Bowls.
  Sun Up Bowl has more great skiing all around, from the open faces all the way to Yonder Trees, which holds fun powder stashes. The lifts of Blue Sky Basin can be accessed from here, although it is a long traverse on a mostly flat cat road, heading down to Chair 9 is a more fun way to get some awesome runs in on the way to Blue Sky Basin, which opens later anyways. Chair 21 and Chair 22 access some of the most remote skiing and snowboarding, and also some of the best powder riding at Vail. Red Square is one of the steepest runs here, and a lot of fun. Genghis Khan is a great run to get down to Chair 37, which leads to Blue Sky basin, where there are a ton of fun glades. Be wary, however, it takes a long time to get back to the base from Blue Sky Basin, so plan accordingly.
  The Vail Village Gondola One, and Golden Peaks Chair 6, can also access all of Vail’s terrain. Golden Peak offers the quickest access to the Back Bowls, but also the coldest start.
  Vail Village, meanwhile, requires a bit of a walk through town to get to the gondola from the bus station or parking garage. It quickly accesses the great beginner and intermediate terrain off of Chairs 3 and 4, however.",
  photo1: "https://www.skisafari.com/sites/default/files/vail-skiers-powder-piste-jack-affleck.jpg", photo2: "https://static.evo.com/content/travel-guides/colorado/vail/vail_4.jpg", photo3: "http://www.snow-trips.com/wp-content/uploads/2014/10/Vail-1.jpg", trail: "https://media.skigebiete-test.de/images/ecu/entity/e_skiresort/ski-resort_vail_n4788-45164-1_pan.jpg", region: "Colorado", tips: "On average, Vail sees 348” of snowfall every season, as well as a huge network of snowmaking. This means that there are plenty of powder days to enjoy throughout the season. While the Back Bowls are the most fun on these powder days, ample Colorado sunshine and stout grooming means there always fun to be had.")
 Resort.create!(name: "Whistler Blackcomb", address: "4050 Whistler Way, Whistler, BC V0N 1B4, Canadá", description: "Year after year, skiers and snowboarders make their way to Whistler Blackcomb from all corners of the world. Whistler Blackcomb has it all, a huge selection of terrain, deep powder, and an amazing town.
  The mountain has an enormous 8,171 acres of skiable terrain that gets blanketed in an average of 462” of snow every winter. There are really two separate mountains, Whistler, and Blackcomb, which are connected by the Peak 2 Peak gondola. The inbounds terrain at Whistler is like a dream come true, there is everything from epic tree skiing and snowboarding, to high alpine bowls, and long groomed runs.
  High on the Blackcomb Glacier, the snow even lasts through the summer, with some of the best freestyle ski camps in the world calling Whistler home.
  Down in the village, there is a great array of shops, restaurants and bars. Everyone from families to skibums will find something to love here.
  All of this awesomeness doesn’t come cheap, however, it makes a good case to put Whistler Blackcomb on your skiing and snowboarding bucket list.
  Whistler:
  Looking at the mountain, Whistler is the mountain to the right, and can be accessed from the Village base or Creekside Base area. Most skiers and snowboarders will want to hop straight onto the Whistler Village Gondola and head to the top. The gondola mid station and Fitzsimmons chair do serve some beginner and intermediate terrain, however. Once at the top of the gondola, options really open up at Whistler. This is also the where the Whistler side of the Peak 2 Peak Gondola loads and unloads. Beginners will want to drop skier’s right to the Emerald Express. Intermediates can do the same, or head skier’s left to the terrain that funnels down to Franz’s Chair. This is a good place for intermediate skiers and snowboarders to get a feel for the exposed alpine terrain higher up at Whistler.
  Options for advanced and expert skiers and snowboarders depend a lot on the weather. Whistler can see the whole spectrum of weather conditions, from dense fog, to beautiful bluebird. Overall, Blackcomb has better terrain for low visibility days. In low visibility, or when waiting for the alpine terrain to open, the best options are to traverse far to either side of the gondola and drop into the trees dropping towards Big Red Express and Emerald Express.
  Once the alpine terrain is open, this is some of the most fun and challenging skiing and snowboarding at Whistler Blackomb. Symphony Express is awesome for beginner skiers and snowboarders that want to try out the alpine.
  Meanwhile advanced and expert riders will want to head to Peak Express to arrive at Whistler’s 7,160’ summit. From here, check out the various chutes and bowls that funnel all the way back to the Creekside Base.
  The runs that head back to Creekside are all rated intermediate and advanced, however, beginners can download the Creekside Gondola.
  Blackcomb:
  Blackcomb also has an awesome assortment of terrain. Whistler may have better beginner terrain off of the gondola mid-station, but Blackcomb is the place to be on stormy and low visibility days. Most skiers and snowboarders will want to get on the Excalibur Gondola and head all the way to the top, then get right on to the Excelerator Express. From here, intermediates will find great cruising on the Solar Coaster lift. This is where the Blackcomb terrain park is located. The park is consistently one of the best in the world. The Blackcomb Peak 2 Peak Gondola station is also located here.
  Around to the skier’s left, the 7th Heaven lift has some of the best intermediate terrain at Whistler Blackcomb. 7th Heaven also accesses some classic lines, like the extreme rated Couloir Extreme.
  There are some easier entrances and some gnarly ones.
  Advanced skiers and snowboarder will want to drop down to the Glacier express and Crystal Ridge chair. The tree skiing and snowboard off of the Crystal Chair is some off the best at Whistler Blackcomb. Spanky’s Ladder is another Blackcomb classic, too.",
  photo1: "https://static.evo.com/content/travel-guides/bc/whistler/mike-crane_i_dualmountain_2014_06.jpg", photo2: "http://www.doglotion.com/wp-content/uploads/2017/01/img_2929-1050x700.jpg", photo3: "https://www.snowmagazine.com/media/reviews/photos/original/71/57/09/10-reasons-why-whistler-is-the-best-ski-resort-in-the-world-90-1499160548.jpg",
  trail: "https://res.cloudinary.com/liftopia/image/upload/c_fit,d_defaults:default_logo_1.png,f_auto,h_980,q_auto,w_980/v1/production/trail_maps/76de432e29103f8a96c3739482a18585.jpg", region: "Canada",
  tips: "Whistler sees everything from deep blower powder days to fun spring slush. The mountain has a huge 5,280’ of vertical drop, so conditions can be very different from the base to the summit, so be ready for anything. The lower mountain can definitely be a bit rainy and foggy from time to time.
  When the sun shines, it’s hard to beat all of the exposed alpine terrain off of the Peak Chair, and on the Blackcomb Glacier. Crowds can get pretty big in Whistler due to the awesome snow and terrain, as well as the easy access, get out early on a powder day.")
 # Resort.create!(name: "", description: "", photo1: "", photo2: "", photo3: "", trail: "", region: "", tips: "")

puts 'finished.'
